# =================
# Markdown-to-Steam
# =================

name: Markdown-to-Steam
author: Shresht7
description: GitHub Action to convert markdown files to steam bb code

# branding:

# Inputs
# ======

inputs:
  file:
    description: "The file to convert"
    default: "README.md"
    required: true

  outDir:
    description: "The target directory"
    default: "."
    required: true

  commitMessage:
    description: "The commit message"
    default: "Update Steam BB-Content"
    required: false

# Run
# ===

runs:
  using: "node12"
  main: "dist/index.js"
