# =================
# Markdown-to-Steam
# =================

name: Markdown-to-Steam
author: Shresht7
description: GitHub Action to convert markdown files to steam bb code

# branding:

# Inputs
# ======

inputs:
  files:
    description: "The file to convert"
    default: "README.md"

  outDir:
    description: "The target directory"
    default: "Documentation"

# Run
# ===

runs:
  using: "node12"
  main: "dist/index.js"
