name: Markdown-to-Steam

# Activation Events
# =================

on:
  # When README.md is updated
  push:
    paths:
      - README.md
  workflow_dispatch: # When a workflow event is dispatched manually

# Jobs
# ====

jobs:
  Markdown-to-Steam:
    runs-on: ubuntu-latest

    name: Markdown-to-Steam
    steps:
      # Actions/Checkout
      # ================

      # Required for GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2

      # Execute Markdown-to-Steam Action
      # ================================

      - name: Markdown-to-Steam
        uses: HunterGhost27/Markdown-to-Steam@main
        id: Markdown-to-Steam

        # Config Parameters
        # -----------------

        with:
          # The list of files to convert
          files: "README.md, CHANGELOG.md"

          # Target directory
          outDir: "Documentation"

        # Environment Variables
        # ---------------------

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to make use of the GitHub API
